language: rust

cache: cargo

rust:
  - stable
  - beta
  - nightly

jobs:
  allow_failures:
    - rust: beta
    - rust: nightly
  fast_finish: true

script:
  - cargo build --verbose
  - cargo test --verbose
  
