[package]
name = "id_tree_layout"
version = "0.1.0"
authors = ["Jörg Singer <singer.joerg@gmx.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
id_tree = { version = "1.7.0", features = ["serde_support"]}
xml_writer = "0.4.0"
serde = "1.0.115"
serde_derive = "1.0.115"
serde_json = "1.0.57"
